[phases.setup]
nixPkgs = ['python311', 'swig']

[phases.build]
cmd = 'python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt'

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port 8000'